# wrangler.toml

name = "monei-api"
compatibility_date = "2023-10-30"
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "monei-db"
database_id = "28504df2-c888-4b8d-a419-97ad6a351968"

[env.production]
vars = { ADMIN_TOKEN = "Kutapira@3902809" }